CREATE TABLE [dbo].[UBIGEO]
(
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DEPUBI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[PROVUBI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DISUBI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UBIGEO] ADD CONSTRAINT [UBIGEO_pk] PRIMARY KEY CLUSTERED ([CODUBI]) ON [PRIMARY]
GO
