CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DESCPRO] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[PREPRO] [decimal] (8, 2) NULL,
[STOCKPRO] [int] NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__PRODUCTO__ESTPRO__33D4B598] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED ([IDPRO]) ON [PRIMARY]
GO
