CREATE TABLE [dbo].[INSUMO]
(
[IDINSU] [int] NOT NULL IDENTITY(1, 1),
[NOMINSU] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DESCINSU] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CANTINSU] [int] NULL,
[ESTINSU] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__INSUMO__ESTINSU__3C69FB99] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INSUMO] ADD CONSTRAINT [INSUMO_pk] PRIMARY KEY CLUSTERED ([IDINSU]) ON [PRIMARY]
GO
