CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[DNICLI] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[NOMCLI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[APEPATCLI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[APEMATCLI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CELCLI] [char] (9) COLLATE Modern_Spanish_CI_AS NULL,
[EMACLI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DOMCLI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NULL,
[ESTCLI] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__CLIENTE__ESTCLI__30F848ED] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED ([IDCLI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
