CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENTDET] [int] NOT NULL IDENTITY(1, 1),
[IDVENT] [int] NULL,
[IDPRO] [int] NULL,
[CANTVENTDET] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED ([IDVENTDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVENT]) REFERENCES [dbo].[VENTA] ([IDVENT])
GO
