CREATE TABLE [dbo].[VENTA]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[FECHVENT] [date] NULL CONSTRAINT [DF__VENTA__FECHVENT__267ABA7A] DEFAULT (getdate()),
[TIPVENT] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDCLI] [int] NULL,
[IDVEND] [int] NULL,
[ESTVENT] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__VENTA__ESTVENT__276EDEB3] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_VENDEDOR] FOREIGN KEY ([IDVEND]) REFERENCES [dbo].[VENDEDOR] ([IDVEND])
GO
